version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=123456789

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8080:80
    environment: 
      - PMA_HOST=mysql
    links:
      - mysql